import * as Y from 'https://esm.sh/yjs@13.6.10';
import { WebsocketProvider } from 'https://esm.sh/y-websocket@3.0.0?deps=yjs@13.6.10';
import { WEBSOCKET_SERVER } from './app-constants.js';

export function createCollaborationController(deps) {
    function waitForInitialSync(provider, timeoutMs = 1500) {
        return new Promise(resolve => {
            let settled = false;

            const finish = () => {
                if (settled) return;
                settled = true;
                clearTimeout(timer);
                resolve();
            };

            const timer = setTimeout(finish, timeoutMs);
            provider.on('sync', isSynced => {
                if (isSynced) finish();
            });
        });
    }

    function disconnectCollaboration() {
        deps.destroyAllBindings();
        if (deps.getProvider()) {
            deps.getProvider().destroy();
            deps.setProvider(null);
        }
        if (deps.getYDoc()) {
            deps.getYDoc().destroy();
            deps.setYDoc(null);
        }

        deps.setSharedMap(null);
        deps.setCheckboxMap(null);
        deps.setLessonsArray(null);
        deps.setRolesArray(null);
        deps.setSharedHistoryArray(null);
        deps.setCurrentRoomId('');
        deps.setSupabaseDocumentId(null);
        deps.setHasBootstrappedInitialRoom(false);
        deps.setRoomWasAutoGenerated(false);
        deps.setRequiresSupabaseHydration(false);
        deps.setActiveRoomReadyPromise(Promise.resolve());
        deps.setResolveActiveRoomReady(null);

        deps.connectionStatus.className = 'status-disconnected';
        deps.connectionStatus.querySelector('.status-text').textContent = '로그인 필요';
        deps.currentRoomNameEl.textContent = '로그인 필요';
        if (deps.collabUsersList) deps.collabUsersList.innerHTML = '';
    }

    async function connectToRoom(roomName) {
        if (!roomName) return;
        const connectionGeneration = deps.bumpRoomConnectionGeneration();
        deps.setCurrentRoomId(roomName);
        deps.currentRoomNameEl.textContent = roomName;
        deps.setSupabaseDocumentId(null);
        deps.setActiveRoomReadyPromise(new Promise(resolve => {
            deps.setResolveActiveRoomReady(resolve);
        }));

        deps.destroyAllBindings();
        if (deps.getProvider()) deps.getProvider().destroy();
        if (deps.getYDoc()) deps.getYDoc().destroy();

        deps.connectionStatus.className = 'status-connecting';
        deps.connectionStatus.querySelector('.status-text').textContent = '연결 중...';

        const ydoc = new Y.Doc();
        deps.setYDoc(ydoc);

        const sharedMap = ydoc.getMap('project-data');
        const checkboxMap = ydoc.getMap('checkbox-states');
        const lessonsArray = ydoc.getArray('lessons-array');
        const rolesArray = ydoc.getArray('roles-array');
        const sharedHistoryArray = ydoc.getArray('project-history');

        deps.setSharedMap(sharedMap);
        deps.setCheckboxMap(checkboxMap);
        deps.setLessonsArray(lessonsArray);
        deps.setRolesArray(rolesArray);
        deps.setSharedHistoryArray(sharedHistoryArray);

        const isCurrentConnection = () => (
            connectionGeneration === deps.getRoomConnectionGeneration() &&
            roomName === deps.getCurrentRoomId() &&
            deps.getYDoc() &&
            deps.getSharedMap() &&
            deps.getLessonsArray() &&
            deps.getRolesArray() &&
            deps.getSharedHistoryArray()
        );

        deps.setupObservers();

        const initialDocument = deps.getCurrentUser()
            ? await deps.resolveSupabaseDocumentByRoom(roomName)
            : null;

        deps.setSupabaseDocumentId(initialDocument?.id || null);

        const provider = new WebsocketProvider(WEBSOCKET_SERVER, roomName, ydoc);
        deps.setProvider(provider);

        provider.on('status', event => {
            if (!isCurrentConnection()) return;
            if (event.status === 'connected') {
                deps.connectionStatus.className = 'status-connected';
                deps.connectionStatus.querySelector('.status-text').textContent = '공동 작업 중';
            } else {
                deps.connectionStatus.className = 'status-disconnected';
                deps.connectionStatus.querySelector('.status-text').textContent = '연결 보류';
            }
        });

        provider.awareness.on('change', () => {
            if (!isCurrentConnection()) return;
            deps.renderActiveUsersList();
            deps.renderFocusedPresenceOutlines();
        });

        provider.awareness.setLocalStateField('user', {
            name: deps.getLocalNickname(),
            color: deps.getLocalColor()
        });

        await waitForInitialSync(provider);
        if (!isCurrentConnection()) return;

        const currentData = deps.getCurrentDocumentData();
        const hasRemoteContent = deps.documentHasMeaningfulContent(currentData);

        if (!hasRemoteContent && initialDocument?.snapshot_json) {
            deps.setRequiresSupabaseHydration(false);
            deps.hydrateDocumentData(initialDocument.snapshot_json);
            deps.setAuthMessage('Supabase 저장본을 불러왔습니다.', 'success');
        } else if (!hasRemoteContent) {
            ydoc.transact(() => {
                deps.initializeDefaultData();
            });
            deps.bindAllStaticElements();
            deps.renderLessonsTable();
            deps.renderRolesTable();
            deps.renderHistoryList();
        } else {
            deps.bindAllStaticElements();
            deps.renderLessonsTable();
            deps.renderRolesTable();
            deps.renderHistoryList();
        }

        const titleText = deps.getSharedMap().get('project-title');
        const docTitle = titleText ? titleText.toString() : '제목 없는 프로젝트';
        deps.updateRecentDoc(deps.getCurrentRoomId(), docTitle);

        const readyResolver = deps.getResolveActiveRoomReady();
        if (readyResolver) {
            readyResolver();
            deps.setResolveActiveRoomReady(null);
        }
    }

    return {
        connectToRoom,
        disconnectCollaboration
    };
}
