export function createDocumentStore(deps) {
    const wait = deps.wait;

    async function bootstrapSupabaseDocumentForRoom() {
        if (!deps.getSupabase() || !deps.getCurrentUser() || !deps.getSharedMap()) {
            return { found: false, hydrated: false };
        }

        const data = await resolveSupabaseDocumentForRoom();
        if (!data) {
            deps.setSupabaseDocumentId(null);
            return { found: false, hydrated: false };
        }

        deps.setSupabaseDocumentId(data.id);

        const currentData = deps.getCurrentDocumentData();
        const shouldForceHydrate = deps.getRequiresSupabaseHydration();
        if (data.snapshot_json && (shouldForceHydrate || !deps.documentHasMeaningfulContent(currentData))) {
            deps.hydrateDocumentData(data.snapshot_json);
            deps.setRequiresSupabaseHydration(false);
            deps.setAuthMessage('Supabase 저장본을 불러왔습니다.', 'success');
            return { found: true, hydrated: true };
        }

        if (shouldForceHydrate) {
            deps.setRequiresSupabaseHydration(false);
        }

        return { found: true, hydrated: false };
    }

    async function findLatestAccessibleDocument() {
        if (!deps.getSupabase() || !deps.getCurrentUser()) return null;

        const { data, error } = await deps.getSupabase()
            .from('documents')
            .select('id, room_id, updated_at')
            .order('updated_at', { ascending: false })
            .limit(1)
            .maybeSingle();

        if (error) {
            deps.setAuthMessage(`최근 문서 확인 실패: ${error.message}`, 'error');
            return null;
        }

        return data;
    }

    async function findAccessibleDocumentByRoom(roomId) {
        if (!deps.getSupabase() || !deps.getCurrentUser() || !roomId) return null;

        const { data, error } = await deps.getSupabase()
            .from('documents')
            .select('id, room_id, updated_at')
            .eq('room_id', roomId)
            .maybeSingle();

        if (error) {
            deps.setAuthMessage(`문서 확인 실패: ${error.message}`, 'error');
            return null;
        }

        return data;
    }

    async function resolveSupabaseDocumentByRoom(roomId) {
        if (!deps.getSupabase() || !deps.getCurrentUser() || !roomId) return null;

        if (deps.getHasCollaborationRpc()) {
            const { data, error } = await deps.getSupabase().rpc('join_document_by_room', {
                p_room_id: roomId
            });

            if (!error) {
                return Array.isArray(data) ? data[0] || null : data || null;
            }

            const missingRpc = /join_document_by_room|Could not find the function|PGRST202/i.test(error.message || '');
            if (!missingRpc) {
                deps.setAuthMessage(`저장 문서 확인 실패: ${error.message}`, 'error');
                return null;
            }

            deps.setHasCollaborationRpc(false);
        }

        const { data, error } = await deps.getSupabase()
            .from('documents')
            .select('id, owner_user_id, room_id, title, snapshot_json, created_at, updated_at')
            .eq('room_id', roomId)
            .maybeSingle();

        if (error) {
            deps.setAuthMessage(`저장 문서 확인 실패: ${error.message}`, 'error');
            return null;
        }

        return data;
    }

    async function maybeSwitchToLatestDocument() {
        if (!deps.getCurrentUser() || !deps.getSupabase()) return false;

        const currentData = deps.getSharedMap() ? deps.getCurrentDocumentData() : null;
        const currentHasMeaningfulContent = currentData ? deps.documentHasMeaningfulContent(currentData) : false;
        const currentDocument = await resolveSupabaseDocumentForRoom();

        if (currentDocument?.id) {
            deps.setSupabaseDocumentId(currentDocument.id);
            deps.setRoomWasAutoGenerated(false);
            return false;
        }

        const shouldSwitchToLatest = deps.getRoomWasAutoGenerated() || !currentHasMeaningfulContent;
        if (!shouldSwitchToLatest) {
            deps.setRoomWasAutoGenerated(false);
            return false;
        }

        const latestDoc = await findLatestAccessibleDocument();
        if (!latestDoc?.room_id || latestDoc.room_id === deps.getCurrentRoomId()) {
            deps.setRoomWasAutoGenerated(false);
            return false;
        }

        deps.setRoomWasAutoGenerated(false);
        window.location.hash = latestDoc.room_id;
        deps.connectToRoom(latestDoc.room_id);
        return true;
    }

    async function forceSwitchToLatestDocument() {
        if (!deps.getCurrentUser() || !deps.getSupabase()) return false;

        const latestDoc = await findLatestAccessibleDocument();
        if (!latestDoc?.room_id) return false;

        deps.setRoomWasAutoGenerated(false);
        if (latestDoc.room_id === deps.getCurrentRoomId()) {
            return true;
        }

        window.location.hash = latestDoc.room_id;
        deps.connectToRoom(latestDoc.room_id);
        return true;
    }

    async function refreshCurrentRoomFromSupabase() {
        await deps.getActiveRoomReadyPromise();

        for (let attempt = 0; attempt < 6; attempt += 1) {
            const result = await bootstrapSupabaseDocumentForRoom();
            if (result?.found) return result;
            await wait(600);
        }

        return { found: false, hydrated: false };
    }

    async function resolveSupabaseDocumentForRoom() {
        return resolveSupabaseDocumentByRoom(deps.getCurrentRoomId());
    }

    function scheduleSupabaseAutoSave() {
        if (!deps.getCurrentUser() || !deps.getSupabase() || !deps.getSharedMap()) return;

        const timer = deps.getSupabaseSaveTimer();
        if (timer) clearTimeout(timer);
        deps.setSupabaseSaveTimer(setTimeout(() => {
            saveCurrentDocumentToSupabase();
        }, 2000));
    }

    async function saveCurrentDocumentToSupabase(options = {}) {
        if (!deps.getCurrentUser() || !deps.getSupabase() || !deps.getSharedMap() || deps.getIsSupabaseSaving()) return;
        deps.setIsSupabaseSaving(true);

        const documentData = deps.getCurrentDocumentData();
        const title = deps.deriveDocumentTitle(documentData);

        try {
            if (!deps.getSupabaseDocumentId()) {
                const existingDoc = await resolveSupabaseDocumentForRoom();
                if (existingDoc) {
                    deps.setSupabaseDocumentId(existingDoc.id);
                }
            }

            if (deps.getSupabaseDocumentId()) {
                const { error } = await deps.getSupabase()
                    .from('documents')
                    .update({
                        title,
                        snapshot_json: documentData,
                        updated_at: new Date().toISOString()
                    })
                    .eq('id', deps.getSupabaseDocumentId());

                if (error) throw error;
            } else {
                const { data, error } = await deps.getSupabase()
                    .from('documents')
                    .insert({
                        owner_user_id: deps.getCurrentUser().id,
                        room_id: deps.getCurrentRoomId(),
                        title,
                        snapshot_json: documentData
                    })
                    .select('id')
                    .single();

                if (error) {
                    const roomAlreadyExists = error.code === '23505' || /duplicate key/i.test(error.message || '');
                    if (roomAlreadyExists) {
                        const joinedDoc = await resolveSupabaseDocumentForRoom();
                        if (joinedDoc) {
                            deps.setSupabaseDocumentId(joinedDoc.id);
                            const { error: retryError } = await deps.getSupabase()
                                .from('documents')
                                .update({
                                    title,
                                    snapshot_json: documentData,
                                    updated_at: new Date().toISOString()
                                })
                                .eq('id', deps.getSupabaseDocumentId());
                            if (retryError) throw retryError;
                        } else {
                            throw error;
                        }
                    } else {
                        throw error;
                    }
                }
                if (data?.id) {
                    deps.setSupabaseDocumentId(data.id);
                }
            }

            if (options.saveVersion && deps.getSupabaseDocumentId()) {
                const { error } = await deps.getSupabase()
                    .from('document_versions')
                    .insert({
                        document_id: deps.getSupabaseDocumentId(),
                        saved_by_user_id: deps.getCurrentUser().id,
                        snapshot_json: documentData
                    });

                if (error) throw error;
            }

            deps.setAuthMessage('로그인된 계정에 자동 저장되었습니다.', 'success');
        } catch (error) {
            deps.setAuthMessage(`자동 저장 실패: ${error.message}`, 'error');
        } finally {
            deps.setIsSupabaseSaving(false);
        }
    }

    return {
        bootstrapSupabaseDocumentForRoom,
        findLatestAccessibleDocument,
        findAccessibleDocumentByRoom,
        resolveSupabaseDocumentByRoom,
        maybeSwitchToLatestDocument,
        forceSwitchToLatestDocument,
        refreshCurrentRoomFromSupabase,
        resolveSupabaseDocumentForRoom,
        scheduleSupabaseAutoSave,
        saveCurrentDocumentToSupabase
    };
}
